#!/bin/sh

set -e

# The script will fail if new includes are not built yet.
for file in includes/*; do
  base=$(basename -- $file)
  name="_includes/${base%.*}.html"
  touch $name
done

# We'd have to build twice to make sure the includes are updated.
bundle exec jekyll build
cp -rv ./_site/includes/* ./_includes/
bundle exec jekyll build

# Validations.
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
